version: "3"
services:
  db-access:
    build: .
    depends_on:
      - tumbleweed-db
    ports:
      - "3000:3000"
  tumbleweed-db:
    image: postgres
    volumes:
      - /Users/ForeignFood/Development/TumbleweedAPI/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DATABASE: "tumbleweed"
